### ISSUE TITLE
[feature] Advanced parameter creation

### ISSUE THREAD

**Issue by GregPK** [nambrot/rspec-api-blueprint-formatter#3]
_(Note: I will gladly implement this, this is more of an FYI and spec for myself)_

Currently we get a basic form of parameters, using just dumped json or the request actually sent via the spec. Nothing wrong with that - gets us up and running quickly. 

However, I would like to add some additional info according with the [Parameter](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-uriparameters-section) specs.

I was thinking something like this is the specs:

```
RSpec.describe '/api/v1/resources', apidoc:true, resource_group: 'Resources' do
  let (:doc_parameters) do 
    {
      some_param: {description: 'So param, very important', default: 0, type: :number, optional: true }
    }
  end
  
  RSpec.describe 'POST /do_something', resource: 'Resource', action: 'Do something', parameters: doc_parameters do
    xhr :post, '[url]', some_param: 56
  end
end
```

Would become:

```
+ Parameters
    + id (number, optional) - So param, very important
        + Default: `0`
```

Some notes:

- I would skip the `<example value>` because it doesn't make sense with rspec generated response bodies (already some example values there).

**Comment by nambrot** [comment]
Thanks for logging this, I really appreciate it.

I'm curious, why using `let` variables over test metadata like the other metadata we are attaching?

**Comment by GregPK** [comment]
It's the same way (metadata). I just gave an example using `:let` because it seems more readable than:

```
RSpec.describe 'POST /do_something', resource: 'Resource', action: 'Do something', 
  parameters: some_param: {description: 'So param, very important', default: 0, type: :number, optional: true } do
  # [....]
end
...

**Comment by nambrot** [comment]
Got it. We might consider recommending writing the metadata a la 

```
post_do_something = {
  action: 'Do something',
  parameters: {
    some_param: {
      description: 'So param, very important',
      # etc.
    }
  {
}
RSpec.describe 'Post /do_somthing', post_do_something.merge(resource: 'Resource') do
end
```

Up to you however
