### ISSUE TITLE
Sourcecode

### ISSUE THREAD

**Issue by jozefvaclavik** [nambrot/rspec-api-blueprint-formatter#5]
So the specs code doesn't really have place in ApiBlueprints. I think its fine to have it, but not inside of a `Request -> Body`. Its breaking then formatting of a Request. Maybe it could 1) optional and if included then 2) moved into `Request -> Schema`. I could do the PR as this is fairly small change.

@nambrot what do you think?

**Comment by nambrot** [comment]
Making this optional totally sounds like a great idea!

Fwiw, the reason we embed the code is to indicate some of the semantics of the behavior of the endpoints that is not clear from the request/response/comments. That being said, I understand that it is not a standard thing
