### ISSUE TITLE
rspec version

### ISSUE THREAD

**Issue by batizhevsky** [nambrot/rspec-api-blueprint-formatter#8]
Hi. 
There a dependency on rspec 3.3, but there used a config option `silence_filter_announcements` that was introduced only in 3.4 version
[https://github.com/rspec/rspec-core/blob/master/Changelog.md](https://github.com/rspec/rspec-core/blob/master/Changelog.md)

**Comment by nambrot** [comment]
Pushed a new version to Rubygems
